name: Issue to PR with Codex

on:
  issues:
    types: [labeled]

jobs:
  fix_with_codex:
    runs-on: ubuntu-latest
    # "codex" ラベルが付いたときだけ動かす
    if: github.event.label.name == 'codex'

    permissions:
      contents: write       # push するので write 必須
      pull-requests: write  # gh pr create 用
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Set git user (bot)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      - name: Generate patch with Codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          BRANCH="codex/issue-${{ github.event.issue.number }}"
          git switch -c "$BRANCH"

          # 依存を一旦クリーン
          rm -rf node_modules || true
          rm -f package-lock.json || true

          cat > /tmp/prompt.txt <<'END_PROMPT'
            ${{ github.event.issue.title }}

            ${{ github.event.issue.body }}

            最後に`npm ci && npm run build`を実行してエラーが無いことを確認してください。.git 直下の隠しファイルは**絶対に編集しない**でください。
            END_PROMPT

          codex exec --full-auto --yes -q "$(cat /tmp/prompt.txt)"

          # Codex が commit してない場合の保険
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Fix: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          fi

          git push -u origin "$BRANCH"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Fix: #${{ github.event.issue.number }} – ${{ github.event.issue.title }}" \
            --body  "Automated fix generated by Codex CLI." \
            --base  main \
            --head  "$BRANCH"
